updated workflow

diff --git a/.github/workflows/sendMessage.yml b/.github/workflows/sendMessage.yml
--- a/.github/workflows/sendMessage.yml
+++ b/.github/workflows/sendMessage.yml
@@ -44,8 +44,15 @@ jobs:
           TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
           MESSAGE="========================================\\nAUTOMATED GITHUB ACTIONS MESSAGE:\\n----------------------------------------\\nCommit made by ${{ github.actor }}: ${{ github.event.head_commit.message }}\\nCommit SHA: ${{ github.sha }}\\nRepository: ${{ github.repository }}\\nBranch: ${{ github.ref }}\\nTimestamp: $TIMESTAMP\\nChanges:\\n$COMMIT_STATS\\n========================================"
           
+          # Ensure bubble_id is not missing
+          BUBBLE_ID="4066670"
+          if [ -z "$BUBBLE_ID" ]; then
+            echo "Error: bubble_id is missing"
+            exit 1
+          fi
+
           # Create JSON payload
-          JSON_PAYLOAD="{\"bubble_id\": \"4066670\", \"created_at\": \"$TIMESTAMP\", \"id\": \"null\", \"message\": \"$MESSAGE\", \"messagemedia\": [], \"user_id\": \"5302367\", \"uuid\": \"${{ env.UUID }}\"}"
+          JSON_PAYLOAD="{\"bubble_id\": \"$BUBBLE_ID\", \"created_at\": \"$TIMESTAMP\", \"id\": \"null\", \"message\": \"$MESSAGE\", \"messagemedia\": [], \"user_id\": \"5302367\", \"uuid\": \"${{ env.UUID }}\"}"
           
           # Print the JSON payload for debugging
           echo "Sending JSON Payload: $JSON_PAYLOAD"
